import { User } from '../configs/interface/UserInterface';

export const dummyData: User[] = [
  {
    id: 0,
    user: {
      boardId: 123,
      title: 'Sample Title',
      content: 'This is an example content for the User object.',
      imgUrl: '../public/img/페트병.png',
      nickname: 'exampleUser',
      date: '2024-05-22',
      latitude: 0,
      longitude: 0,
      password: '1234',
    },
    created: '2024-05-12',
    title: '나눔',
    content: '재활용해요',
  },
  {
    id: 0,
    user: {
      boardId: 123,
      title: 'Sample Title',
      content: 'This is an example content for the User object.',
      imgUrl: '../img/페트병.png',
      nickname: 'exampleUser',
      date: '2024-05-22',
      latitude: 0,
      longitude: 0,
      password: '1234',
    },
    created: '2024-05-12',
    title: '나눔',
    content: '재활용해요',
  },
  {
    id: 0,
    user: {
      boardId: 123,
      title: 'Sample Title',
      content: 'This is an example content for the User object.',
      imgUrl: '../img/페트병.png',
      nickname: 'exampleUser',
      date: '2024-05-22',
      latitude: 0,
      longitude: 0,
      password: '1234',
    },
    created: '2024-05-12',
    title: '나눔',
    content: '재활용해요',
  },
];
